### ISSUE TITLE
April 9

### ISSUE THREAD

**Issue by SevlaMare** [SevlaMare/bubble_sort_ruby#4]

**Comment by ferbaco86** [comment]
- In your README.md file, you have a parenthesis at the end of the Twitter and Linkedin link like it shows in the picture attached.
![Captura de Pantalla 2020-04-09 a la(s) 10 27 26](https://user-images.githubusercontent.com/52765379/78906678-a6ef6a00-7a4d-11ea-9e51-99c7f6c318e7.png)

**Comment by FrancoRosa** [comment]
# Great Project!

I was playing around **with variable n** It seems that it does not change.
I intentionally erased in the following code, it seems to work.
```
def bubble_sort(array)
  trigger = true
  while trigger
    # if no swap, so is already sorted
    trigger = false

    # each lap do (n-1)
    # because last element it's already sorted
    (0...array.length - 1).each do |i|
      next unless array[i] > array[i + 1]
      array[i], array[i + 1] = array[i + 1], array[i]
      puts [array[i], array[i + 1]].inspect
      # if one swap in the whole lap, start again
      trigger = true
    end
    puts array.inspect

  end
  array
end
```

**Comment by SevlaMare** [comment]
All fixed.
